### ISSUE TITLE
Support borrowed-from-unsized keys

### ISSUE THREAD

**Issue by kennytm** [nabijaczleweli/bidir-map-rs#1]
Current `get`, `get_mut`, `contains` and `remove` methods expect a borrowed-from-sized key, which makes the following fail to compile:

``` rust
let map = BidirMap::<String, usize>::new();
map.get_by_first("1234");
```

```
src/aaa.rs:22:9: 22:21 error: the trait `core::marker::Sized` is not implemented for the type `str` [E0277]
src/aaa.rs:22     map.get_by_first("1234");
                      ^~~~~~~~~~~~
src/aaa.rs:22:9: 22:21 help: run `rustc --explain E0277` to see a detailed explanation
src/aaa.rs:22:9: 22:21 note: `str` does not have a constant size known at compile-time
```

---

The problem is the [signature of these functions](https://github.com/nabijaczleweli/bidir-map-rs/blob/fc74f480db6c57966d8c45a98d138e17bcb0b2d6/src/lib.rs#L215-L217) does not declare `Q: ?Sized`. It should read:

``` rust
    pub fn get_by_first<Q: ?Sized>(&self, key: &Q) -> Option<&Kv2>
        where Kv1: Borrow<Q>,
              Q  : PartialEq<Kv1>,
```

**Comment by nabijaczleweli** [comment]
Good catch, fix will be up soon

**Comment by nabijaczleweli** [comment]
Tagged in https://github.com/nabijaczleweli/bidir-map-rs/releases/tag/v0.3.0, published on `crates.io`
