### ISSUE TITLE
get_by_first docs accidental copy-paste of get_by_second

### ISSUE THREAD

**Issue by evmar** [nabijaczleweli/bidir-map-rs#2]
The docstring is wrong, it gets "first" and "second" backwards:

https://github.com/nabijaczleweli/bidir-map-rs/blob/9724bcd57edb386d9fe76a5461738309ce72a5eb/src/lib.rs#L203

**Comment by nabijaczleweli** [comment]
You're damn right it's a copypaste error.

**Comment by nabijaczleweli** [comment]
Released in [`v0.3.1`](https://github.com/nabijaczleweli/bidir-map-rs/releases/tag/v0.3.1)
