### ISSUE TITLE
Eliminating unsafe code

### ISSUE THREAD

**Issue by Boscop** [nabijaczleweli/bidir-map-rs#3]
Casting &T to &mut T is UB.
This should probably use iter_mut():
https://cdn.rawgit.com/nabijaczleweli/bidir-map-rs/doc/src/bidir_map/src/lib.rs.html#298
https://cdn.rawgit.com/nabijaczleweli/bidir-map-rs/doc/src/bidir_map/src/lib.rs.html#322

**Comment by nabijaczleweli** [comment]
I've just got this fixed right now :P
Thanks, Shep, for bringing this to my attention

**Comment by nabijaczleweli** [comment]
Released in [`v0.3.3`](https://github.com/nabijaczleweli/bidir-map-rs/releases/tag/v0.3.3).
Enjoy!
