### ISSUE TITLE
Consider making access more like HashMap

### ISSUE THREAD

**Issue by Boscop** [nabijaczleweli/bidir-map-rs#7]
When converting some code from using HashMap to using BidirMap, one has to change things like `m.iter().map(|(a, &b)|` to `m.iter().map(|&(ref a, b)|`. Is this intentional?
Also, one has to change `m[key]` to `*m.get_by_first(key)` (with dereference).
I'd prefer if the API was more similar to HashMap (same syntax for iter() and no deref for `get`).
Also, I think it would make sense to have an `Index` impl that has the same API as HashMap but uses `get_by_first` (because even with a `BidirMap`, `get_by_first` will be the most common lookup direction and if there is an `Index` impl, it will be assumed that it is `get_by_first`).

IMO this would increase the ergonomics of BidirMap :)

**Comment by nabijaczleweli** [comment]
After https://github.com/nabijaczleweli/bidir-map-rs/commit/97989cef0604955a11e255a1265be926a88e3303, iterators have `&`s in the same place as those of `BTreeMap` (i.e. `(&,&)` rather than `&(,)`).

After https://github.com/nabijaczleweli/bidir-map-rs/commit/1dbfa2ba27878bda48b0bd005f75fecd8c537491, you can use `bmap[ByFirst(key)]` like `BTreeMap`'s `map[key]`.

How'd you like that?

**Comment by Boscop** [comment]
Thanks, I like the first change, but TBH I don't think `bmap[ByFirst(key)]` is more ergonomic than `bmap.get_by_first(key)`. 
I'd prefer `bmap[key]` to be equivalent to [`bmap.get_by_first(key).expect("no entry found for key")`](https://doc.rust-lang.org/src/std/collections/hash/map.rs.html#1334) (because most uses of BidirMap are `get_by_first` nonetheless).

**Comment by nabijaczleweli** [comment]
> most uses of BidirMap are `get_by_first` nonetheless

Well, that claim is unprovable and to assert that would be to severely limit its usability (also, it screams "XY" :v).

If the rest's good (as you said it is), I'm releasing.

**Comment by nabijaczleweli** [comment]
Released in [`v1.0.0`](https://github.com/nabijaczleweli/bidir-map-rs/releases/tag/v1.0.0)
